apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-proj-deployment
  labels:
    app: capstone-proj
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone-proj
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone-proj
    spec:
      containers:
        - image: elnaggar3012/capstone-proj
          imagePullPolicy: Always
          name: capstone-container
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: capstone-lb-service
  labels:
    app: capstone-proj
spec:
  type: LoadBalancer
  selector:
    app: capstone-proj
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP